name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Playwright Browsers
      run: playwright install --with-deps chromium
      
    - name: Run Pytest
      run: pytest
      
    - name: Install Allure Commandline
      if: always()
      run: |
        wget https://github.com/allure-framework/allure2/releases/download/2.32.0/allure-2.32.0.tgz
        tar -zxvf allure-2.32.0.tgz
        sudo ln -s $(pwd)/allure-2.32.0/bin/allure /usr/local/bin/allure

    - name: Generate Allure Report
      if: always()
      run: allure generate allure_results -o allure-report --clean

    - name: Generate Pulse Report
      if: always()
      run: |
        mkdir -p pulse-report/pulse-report-1 pulse-report/pulse-report-2 pulse-report/pulse-report-3 pulse-report/pulse-report-4 && \mv pulse-report/.pulse-shard-results-0.json pulse-report/pulse-report-1/playwright-pulse-report.json && \mv pulse-report/.pulse-shard-results-1.json pulse-report/pulse-report-2/playwright-pulse-report.json && \mv pulse-report/.pulse-shard-results-2.json pulse-report/pulse-report-3/playwright-pulse-report.json && \mv pulse-report/.pulse-shard-results-3.json pulse-report/pulse-report-4/playwright-pulse-report.json && \mv pulse-report/.pulse-shard-results-4.json pulse-report/pulse-report-5/playwright-pulse-report.json && \mv pulse-report/.pulse-shard-results-5.json pulse-report/pulse-report-6/playwright-pulse-report.json
        merge-pulse-report
        rm -rf pulse-report/playwright-pulse-report.html && rm -rf pulse-report/playwright-pulse-static-report.html
        generate-report
        generate-pulse-report
        generate-email-report
      
    - name: Upload Pytest HTML Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-html-report
        path: reports/
        retention-days: 14

    - name: Upload Raw Allure Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure_results/
        retention-days: 14

    - name: Upload Generated Allure Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-html-report
        path: allure-report/
        retention-days: 14

    - name: Upload Pulse Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pulse-report
        path: pulse-report/
        retention-days: 14    
